[project]
name = "progressive_py"
version = "0.1.0"
description = "Elegant, customizable progress bars and spinners for Python — in both terminal and Jupyter notebook environments!"
authors = [
    { name = "Muhammad Abubakar Siddique Ansari", email = "ansaricodes@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "IPython",
    "colorama>=0.4.6"
]

[project.urls]
Homepage = "https://github.com/Ansari-Codes/progressive_py.git"

[tool.setuptools]
packages = ["progressive_py"]
include-package-data = true

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"